version: "3.8"
   
services:
  postgres:
    image: postgres:14.5
    container_name: soc_postgres
    restart: always
    environment:
      POSTGRES_USER: soc_user
      POSTGRES_PASSWORD: Shadows0fCha0s
      POSTGRES_DB: soc_db
      POSTGRES_PORT: 5432
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: pg_isready -U soc_user -d soc_db
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    build: 
      dockerfile: Dockerfile
    ports:
        - "80:80" 
    depends_on:
      postgres:
        condition: service_healthy
  pgadmin:
    container_name: pgadmin4_soc
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: paradox_zero@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 127.0.0.1:5354:80
  